# Generated by Django 3.1.5 on 2021-03-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AadharNumber', models.IntegerField()),
                ('cdesc', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Dl_table',
            fields=[
                ('AadharNumber', models.IntegerField()),
                ('Name', models.CharField(max_length=25)),
                ('cov', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('City', models.CharField(max_length=15)),
                ('dl_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='llr_table',
            fields=[
                ('llr_id', models.AutoField(primary_key=True, serialize=False)),
                ('AadharNumber', models.IntegerField()),
                ('Name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=15, unique=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('dateofbirth', models.DateField()),
                ('City', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=6)),
                ('VehicleType', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='registration_table',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('aadharNumber', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('cov', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=25, unique=True)),
                ('model', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('reg_issue_date', models.DateField()),
                ('reg_expiry_date', models.DateField()),
                ('mail_id', models.EmailField(max_length=254)),
                ('Gender', models.CharField(max_length=8)),
                ('fuel_type', models.CharField(max_length=9)),
                ('vehicle_category', models.CharField(max_length=7)),
            ],
        ),
    ]
